### ISSUE TITLE
Use getters instead of `getX()`

### ISSUE THREAD

**Issue by NSExceptional** [ghjbnm/youtube-dl-wrap#12]
It makes your API more ergonomic if I can just do `.version` instead of `.getVersion()` for example :)

More on getters [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) in case you are unfamiliar

**Comment by ghjbnm** [comment]
Property Getters causing ipc is imo unexpected behavior and should be avoided. I will leave it as it is.
