### ISSUE TITLE
Support `"exit"` event

### ISSUE THREAD

**Issue by NSExceptional** [ghjbnm/youtube-dl-wrap#13]
Looking at your source code, it looks like you only support `"close"`

**Comment by ghjbnm** [comment]
If you really need the exit event for some reason you can access the youtubeDlProcess property.
Since the EventEmitter/ReadableStream only wraps the stderr/stdout I don't think it makes sense to additionally expose the exit event there.

**Comment by NSExceptional** [comment]
Oh, true. Thanks
