### ISSUE TITLE
how to readableStream.pipe(res) with express

### ISSUE THREAD

**Issue by mirsella** [ghjbnm/youtube-dl-wrap#16]
```
app.get('/', async (req,res) =>{
  // res.header('Content-Disposition', `attachment; filename="audio.mp3"`);
  // res.attachment('test.mp3')
  let msq = ytdl.execStream(["https://www.youtube.com/watch?v=3r9vJI5OiV8", "--audio-format", "mp3", "-f", "bestaudio"])
    .on("progress", (progress) => console.log(progress.percent, progress.totalSize, progress.currentSpeed, progress.eta))
    .on("youtubeDlEvent", (eventType, eventData) => console.log(eventType, eventData))
    .on("error", (error) => console.error(error))
    .on("close", () => console.log("all done"))
  msq.pipe(res)
});
```

it works and i receive the file, but the download just hang and doesn't finish.

![image](https://user-images.githubusercontent.com/45905567/132484270-dadd599b-84a8-41ef-82dd-c6296e804432.png)
if i ctrl+C wget  the file works.

thanks

**Comment by ghjbnm** [comment]
Seems like an express problem to me. The function probably shouldn't return until the stream is closed, but no clue.

**Comment by mirsella** [comment]
so no async ?

**Comment by ghjbnm** [comment]
async what? If you need to wait for the Stream to end wrap it in a Promise. If you dont need a Stream just use execPromise.

**Comment by mattoz0** [comment]
Yeah execStream never returns because not all the correct events are passed. Same issues as #4
