### ISSUE TITLE
seemly it doesn't work with ffmpeg parameter

### ISSUE THREAD

**Issue by huynv86** [ghjbnm/youtube-dl-wrap#2]
"-f", "bestvideo+bestaudio", "--prefer-ffmpeg", "--ffmpeg-location", "ffmpeg.exe"
I try with parameters as above. It only downloads video and audio files but doesn't merge them in to mp4

**Comment by ghjbnm** [comment]
Afaik you need to add --merge-output-format mp4.

**Comment by ghjbnm** [comment]
@huynv86 Did it solve your problem or does the issue persist?

**Comment by huynv86** [comment]
i am so sorry for late reply
I didn't try your solution but i fixed it by using one more package for merging video and audio
I still use your package for downloading only
Thank you so much, your package really saves my life!!!

**Comment by ghjbnm** [comment]
@huynv86 After trying it myself I think the issue is most likely caused by an incorrect ffmpeg location.
