### ISSUE TITLE
Merge work

### ISSUE THREAD

**Issue by brunobg** [ghjbnm/youtube-dl-wrap#3]
Hi, somehow I missed this package and I was working on https://github.com/Corollarium/youtubedl-wrapper. I seem to be duplicating work you're doing. Perhaps we should merge projects? I could port differences to this project, like getting thumbnails. What do you think?

**Comment by ghjbnm** [comment]
Hey, saving thumbnails can be done simply with youtube-dl (--write-thumbnail --skip-download), not sure if I want to add a method for that. Otherwise I don't think there is much to merge, but if you have any other suggestions let me know.

**Comment by brunobg** [comment]
Sure, but all of it is "simply youtube-dl xxxx", and thumbnails are useful to me. I also plan to add a couple extra things, like handling playlists.

**Comment by ghjbnm** [comment]
I want to keep the project small and just provide a simple Interface. I think utility function related to videos should be for the user to implement.
