### ISSUE TITLE
TypeError: Cannot create property 'message' on string.

### ISSUE THREAD

**Issue by mattoz0** [ghjbnm/youtube-dl-wrap#4]
`TypeError: Cannot create property 'message' on string 'error - 1 -  - [youtube] 5ZH2it92ZmA: Downloading webpage
ERROR: 5ZH2it92ZmA: YouTube said: Unable to extract video data
`

This error is currently happening on version 1.1.2.

This is because a string is passed in instead of an error object to the Readable.destroy method.

The below code would fix the issue.
`
youtubeDlProcess.on("close", (code) => {
            readStream.destroy(new Error(code == 0 ? false : "error - " + code + " - " + processError + " - " + stderrData));
        });
`

**Comment by mattoz0** [comment]
This issue stopped appearing after piping through ffmpeg. Its still not great that its expecting an Error object and we are sending a string, but i can live with it.

**Comment by mattoz0** [comment]
I've done a bunch of digging into this, the execStream function doesn't really work. It returns a stream however none of the stream events pass through. So in the example of a music bot it will never know when to change songs. Additionally as mentions above the error is incorrect.

`youtubeDlProcess.on("close", (code) => { readStream.destroy(code == 0 ? false : new Error("error - " + code + " - " + processError + " - " + stderrData)); });`
I believe it should be this, however it only fixes the type error that fatal crashes it doesn't actually fix the stream issues.

**Comment by ghjbnm** [comment]
I added the progress event to the Readable Stream, other possible events are not implemented yet.
Not sure when I will do that, if you want you can also make a merge request which implements more events.

**Comment by mattoz0** [comment]
Yeah I'll drop a PR later today. I was doing some extensive testing last night. I'm pretty satisfied the code in my fork solves the issue.
