### ISSUE TITLE
Stream events not ending

### ISSUE THREAD

**Issue by HMLarsen** [ghjbnm/youtube-dl-wrap#9]
Hi! Thanks for the great lib!
I'm using the `youtubeDlWrap.execStream` method for download living videos from Youtube. And I include in my code the `youtubeDlEvent` events listener to that stream:

```
return youtubeDlWrap.execStream([YOUTUBE_VIDEO_URL + liveId,
	'-f', 'best',
	'--youtube-skip-dash-manifest',
	'--hls-use-mpegts',
	'--ffmpeg-location', pathToFfmpeg])
.on('youtubeDlEvent', (eventType, eventData) => console.log('[youtubeDlEvent] - ' + eventType, eventData));
```
But even that stream is destroyed/closed/ended the `youtubeDlEvent` is emitted. My code below to try shutdown the stream:
```
if (!ytdlStream.destroyed) {
	ytdlStream.end();
}
ytdlStream.removeAllListeners('data');
ytdlStream.destroy();
ytdlStream = null;
```
The `data` events are correctly shutdown but `youtubeDlEvent` still remaining printing in the console.
I have this code running im my Heroku application and in closed times the app's memory is reaching the Heroku limits and I think this could be the problem.

**Comment by ghjbnm** [comment]
I think that happens because you don't kill the spawned process, which you can access by using `ytdlStream.youtubeDlProcess`.
I will consider adding a cancelToken parameter for that purpose.

**Comment by HMLarsen** [comment]
In fact, with more research on the subject, I managed to kill the process as you commented and the events stopped ... I imagine that everything was released this time.
This is my code to destroy the stream and the child process...
```
// destroy its stream
if (!data.ytdlStream.destroyed) {
	data.ytdlStream.removeAllListeners('close'); // to not call this method again when spawn is killed (lib implementation)
	data.ytdlStream.destroy();
}
// destroy spawn process created from lib related to download stream
if (data.ytdlStream.youtubeDlProcess) {
	data.ytdlStream.youtubeDlProcess.stdin.destroy();
	data.ytdlStream.youtubeDlProcess.stdout.destroy();
	data.ytdlStream.youtubeDlProcess.stderr.destroy();
	data.ytdlStream.youtubeDlProcess.kill();
	data.ytdlStream.youtubeDlProcess = null;
}
data.ytdlStream = null;
```
Can anything about this way of ending everything be improved? Can you show me some sample code on this?
And what is `cancelToken` parameter that you commented about?

**Comment by ghjbnm** [comment]
Just killing the process should be enough and setting data.ytdlStream to null should be enough.

**Comment by HMLarsen** [comment]
Thank you!!
